services:
  nextjs-app:
    build:
      context: ./frontend/next-js
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    volumes:
      - ./frontend/next-js:/app
      - /app/node_modules

  nestjs-app:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "3050:3050"
    volumes:
      - ./backend:/app
      - /app/node_modules
  postgres:
    image: postgres:latest
    environment:
      POSTGRES_DB: postgres-db
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
    ports:
      - "5433:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data

volumes:
  postgres-data: