name: Backend CI/CD

on:
  push:
    paths:
      - "backend/**"

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3  # Обновлено до последней версии

      - name: Setup Node.js
        uses: actions/setup-node@v3  # Обновлено до последней версии
        with:
          node-version: "20.11.0"
          cache: "pnpm"

      - name: Install pnpm
        run: npm install -g pnpm

      - name: Install dependencies
        run: cd backend && pnpm install

      - name: Run tests
        run: cd backend && pnpm test

      - name: Build
        run: cd backend && pnpm run build
