name: Backend CI/CD

on:
  push:
    paths:
      - "backend/**"

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "20.11.0"
          cache: "pnpm"

      - name: Setup pnpm
        uses: pnpm/action-setup@v2.0.1
        with:
          version: 7.x

      - name: Install dependencies
        run: cd backend && pnpm install

      - name: Run tests
        run: cd backend && pnpm test

      - name: Build
        run: cd backend && pnpm run build
